server {
    listen 80;
    server_name _;
    absolute_redirect off;
    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;

    location = / {
        return 302 /cambel/;
    }

    location = /cambel {
        return 301 /cambel/;
    }

    location /cambel/ {
        alias /usr/share/nginx/html/;
        index index.html;
    }

    location /diagnostico {
        proxy_pass http://quiz:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
        proxy_buffering off;
        client_max_body_size 8m;
    }
}
